moves Viper tools version to a separate file

diff --git a/artifact/Dockerfile b/artifact/Dockerfile
--- a/artifact/Dockerfile
+++ b/artifact/Dockerfile
@@ -71,40 +71,50 @@ WORKDIR $HOME
 # - tag (e.g. "v.21.01-release")
 # - commit hash or
 # - branch name (e.g. "origin/artifact" - note the leading "origin/")
-ENV SILVER_COMMIT "v.21.07-release"
-ENV CARBON_COMMIT "v.21.07-release"
-ENV SILICON_COMMIT "v.21.07-release"
-# GOBRA_COMMIT can be set while building the docker image by using `docker build --build-arg GOBRA_COMMIT=<some branch>`
+# GOBRA_REF can be set while building the docker image by using `docker build --build-arg GOBRA_REF=<some branch>`
 # by default, "origin/artifact1" is used:
-ARG GOBRA_COMMIT="origin/artifact1"
-# store GOBRA_COMMIT ARG in an environment variable with the same name such that it is still available after building
+ARG GOBRA_REF="origin/artifact1"
+ARG SILVER_REF
+ARG CARBON_REF
+ARG SILICON_REF
+# store GOBRA_REF ARG in an environment variable with the same name such that it is still available after building
 # the container:
-ENV GOBRA_COMMIT $GOBRA_COMMIT
+ENV GOBRA_REF $GOBRA_REF
+ENV SILVER_REF $SILVER_REF
+ENV CARBON_REF $CARBON_REF
+ENV SILICON_REF $SILICON_REF
+# Check build arguments
+RUN if [ -z "$SILVER_REF" ]; then echo "SILVER_REF is required" && exit 1 ; fi
+RUN if [ -z "$CARBON_REF" ]; then echo "CARBON_REF is required" && exit 1 ; fi
+RUN if [ -z "$SILICON_REF" ]; then echo "SILICON_REF is required" && exit 1 ; fi
 # all commands are executed as part of a single "RUN" command in order that no intermediate layers with
 # temporary files get created
 RUN cd $HOME && \
     # setup silver
     git clone https://github.com/viperproject/silver.git $HOME/silver && \
     cd $HOME/silver && \
-    git reset --hard $SILVER_COMMIT && \
+    git reset --hard $SILVER_REF && \
+    echo "Switched to Silver commit $SILVER_REF" && \
     cd $HOME && \
     # setup carbon
     git clone https://github.com/viperproject/carbon.git $HOME/carbon && \
     cd $HOME/carbon && \
-    git reset --hard $CARBON_COMMIT && \
+    git reset --hard $CARBON_REF && \
+    echo "Switched to Carbon commit $CARBON_REF" && \
     ln --symbolic $HOME/silver && \
     cd $HOME && \
     # setup silicon
     git clone https://github.com/viperproject/silicon.git $HOME/silicon && \
     cd $HOME/silicon && \
-    git reset --hard $SILICON_COMMIT && \
+    git reset --hard $SILICON_REF && \
+    echo "Switched to Silicon commit $SILICON_REF" && \
     ln --symbolic $HOME/silver && \
     cd $HOME && \
     # setup gobra
     git clone https://github.com/viperproject/gobra.git $HOME/gobra && \
     cd $HOME/gobra && \
-    git reset --hard $GOBRA_COMMIT && \
-    echo "Switched to Gobra commit $GOBRA_COMMIT" && \
+    git reset --hard $GOBRA_REF && \
+    echo "Switched to Gobra commit $GOBRA_REF" && \
     ln --symbolic $HOME/silver && ln --symbolic $HOME/silicon && ln --symbolic $HOME/carbon && \
     # empty src/test/resources/regressions and src/test/resources/same_package such that no test files end up in the JAR
     rm -r src/test/resources/regressions/* && \
